### ISSUE TITLE
[admin] resource name are missing in all href urls after creating resource

### ISSUE THREAD

**Issue by kernicPanel** [bigcompany/resources#2]
I'm not sure if it's a big, resource or admin resource issue…
Sorry if it's not the right place to post this issue.

After install, I to to http://localhost:8888/admin/resources/creature
I click create -> http://localhost:8888/admin/resources/creature/create
I create a creature -> http://localhost:8888/admin/resources/creature/create
I click all -> http://localhost:8888/admin/resources/all/54cd5c01-ac31-412e-a6cb-1b5393000668 

``` js
Throws error :
TypeError: Cannot read property 'methods' of undefined
    at module.exports [as present] (/home/nc/projects/bigTest/resources/admin/view/method.js:7:17)
    at /home/nc/projects/bigTest/resources/admin/index.js:144:17
    at callbacks (/home/nc/projects/bigTest/node_modules/express/lib/router/index.js:160:37)
    at module.exports (/home/nc/projects/bigTest/node_modules/connect/lib/middleware/basicAuth.js:96:9)
    at callbacks (/home/nc/projects/bigTest/node_modules/express/lib/router/index.js:160:37)
    at param (/home/nc/projects/bigTest/node_modules/express/lib/router/index.js:134:11)
    at param (/home/nc/projects/bigTest/node_modules/express/lib/router/index.js:131:11)
    at param (/home/nc/projects/bigTest/node_modules/express/lib/router/index.js:131:11)
    at pass (/home/nc/projects/bigTest/node_modules/express/lib/router/index.js:141:5)
    at Router._dispatch (/home/nc/projects/bigTest/node_modules/express/lib/router/index.js:169:5)
```

All methods href seems broken on page after ressource create : resource name are missing in urls

**Comment by jfhbrook** [comment]
I didn't get this error, but I did find that the /admin/resources/all/{id} routes weren't exposing the correct urls. I fixed this in https://github.com/bigcompany/resources/commit/5438a4e05e3d7ca732624265d76aebc7614e8596 .

Thanks!
